import Head from "next/head";
import Header from "../components/shared/Header/Header";
import Hero from "../components/shared/Hero/Hero";

import heroImage from "../assets/images/home/group.jpg";
import Pole from "../components/Home/Pole/Pole";
import Footer from "../components/shared/Footer/Footer";
import api from "../services/api";

export async function getServerSideProps() {
  const res = await api.get("/poles?populate=*");

  return {
    props: { poles: res.data.data }, // will be passed to the page component as props
  };
}

const Equipe = ({ poles }) => {
  return (
    <>
      <Head>
        <title>Lucky Fox | L'équipe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Hero imageURL={heroImage} title="L'équipe" />

      <main className="main">
        <section className="section dark">
          <h2 className="sectionTitle">Notre équipe</h2>

          {poles.map((pole) => {
            return (
              <Pole
                key={pole.id}
                name={pole.attributes.name}
                members={pole.attributes.membres.data}
              />
            );
          })}
        </section>
      </main>
      <Footer />
    </>
  );
};

export default Equipe;
