import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import Header from "../components/shared/Header/Header";

import styles from "../styles/pages/Home.module.scss";

import heroImage from "../assets/images/hero/hero.jpg";
import groupImage from "../assets/images/home/group.jpg";
import collabImage from "../assets/images/home/partenaires.jpg";

import List from "../components/Home/List/List";
import Member from "../components/Home/Member/Member";

import BigArrow from "../assets/icons/bigArrow.svg";

import Hero from "../components/shared/Hero/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Hero
        imageURL={heroImage}
        title="Lucky Fox"
        text="Liste BDE 2022-2023"
        isIndex={true}
      />

      {/* <section className="hero">
        <Image
          className="heroImg"
          src={heroImage}
          width={5934}
          height={3709}
          layout="fill"
        />
        <div className="heroContent">
          <div className="heroText">
            <div className="textContainer">
              <h1 className="heroTitle">Lucky Fox</h1>
            </div>
            <div className="textContainer">
              <h2 className="heroSubTitle">Liste BDE</h2>
            </div>
          </div>

          <div className="heroShadow"></div>
        </div>

        <Sound onClick={() => play()} className={styles.soundIcon} />

        <Mouse className="mouse" />
      </section> */}

      <main className="main">
        <section className="section dark">
          <h2 className={`sectionTitle ${styles.mobileTitle}`}>Notre équipe</h2>
          <div className="sectionRow">
            <div>
              <h2 className={`sectionTitle ${styles.desktopTitle}`}>
                Notre équipe
              </h2>

              <p className={styles.paragraph}>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                Facilis aliquam omnis, eveniet sed dolorum alias quis ratione
                labore, id voluptatem vero? Rem corporis commodi mollitia animi
                assumenda necessitatibus exercitationem tempore. Esse omnis a
                ullam rerum ducimus autem exercitationem, voluptatem nam harum
                deleniti? A temporibus blanditiis aperiam quam repudiandae
                labore atque impedit pariatur vero autem, ad suscipit illum
                quisquam, recusandae cumque molestias! Amet, sit! Ut quasi
                architecto numquam suscipit repellat minima dignissimos laborum
                sint, esse vel? Facere quo ex, cumque reiciendis rem modi
                similique ullam atque ea cum debitis, maxime quia tempora
                ducimus incidunt. Consectetur quia rerum veritatis facilis
                repellendus nisi!
              </p>
              <Link href="/membres">
                <a className={styles.sectionLink}>
                  <span className="sectionLink">Voir nos membres</span>
                  <BigArrow className={styles.arrow} />
                </a>
              </Link>
            </div>
            <div className={styles.sectionImgContainer}>
              <Image
                className={styles.sectionImg}
                src={groupImage}
                layout="fill"
              />
            </div>
          </div>
        </section>
        <section className="section">
          <h2 className={`sectionTitle ${styles.mobileTitle}`}>
            Nos partenaires
          </h2>
          <div className="sectionRow">
            <div className={styles.sectionImgContainer}>
              <Image
                className={styles.sectionImg}
                src={collabImage}
                layout="fill"
              />
            </div>
            <div>
              <h2 className={`sectionTitle ${styles.desktopTitle}`}>
                Nos partenaires
              </h2>

              <p className={styles.paragraph}>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                Facilis aliquam omnis, eveniet sed dolorum alias quis ratione
                labore, id voluptatem vero? Rem corporis commodi mollitia animi
                assumenda necessitatibus exercitationem tempore. Esse omnis a
                ullam rerum ducimus autem exercitationem, voluptatem nam harum
                deleniti? A temporibus blanditiis aperiam quam repudiandae
                labore atque impedit pariatur vero autem, ad suscipit illum
                quisquam, recusandae cumque molestias! Amet, sit! Ut quasi
                architecto numquam suscipit repellat minima dignissimos laborum
                sint, esse vel? Facere quo ex, cumque reiciendis rem modi
                similique ullam atque ea cum debitis, maxime quia tempora
                ducimus incidunt. Consectetur quia rerum veritatis facilis
                repellendus nisi!
              </p>
              <Link href="/partenaires">
                <a className={styles.sectionLink}>
                  <span className="sectionLink">Voir nos partenaires</span>
                  <BigArrow className={styles.arrow} />
                </a>
              </Link>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
