import Head from "next/head";
import Header from "../components/shared/Header/Header";
import Hero from "../components/shared/Hero/Hero";

import heroImage from "../assets/images/home/partenaires.jpg";

import styles from "../styles/pages/Collaborators.module.scss";
import { useState } from "react";
import Collaborator from "../components/Collaborators/Collaborator";

import BigArrow from "../assets/icons/bigArrow.svg";
import Link from "next/link";
import Footer from "../components/shared/Footer/Footer";
import api from "../services/api";

export async function getServerSideProps(context) {
  const res = await api.get("/collaborateurs?populate=*");

  return {
    props: { collaborators: res.data.data }, // will be passed to the page component as props
  };
}

const Collaborators = ({ collaborators }) => {
  const [selected, setSelected] = useState(null);

  return (
    <>
      <Head>
        <title>Lucky Fox | Partenaires</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Hero imageURL={heroImage} title="Nos partenaires" />

      <main className="main">
        <section className="section dark">
          <h2 className="sectionTitle">Bla bla bla</h2>
          <p className="paragraph">
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestiae,
            aperiam a. Ut incidunt omnis molestias voluptatibus cupiditate.
            Ducimus tempora reiciendis, quod ex modi tenetur eveniet fuga omnis
            iure harum distinctio aliquam iste et beatae id, quo neque
            consequuntur voluptates blanditiis deserunt labore enim. Quos error
            sint aperiam ex unde? Aperiam, quaerat incidunt? Blanditiis magni
            cum tenetur.
          </p>
        </section>
        <section className="section">
          <h2 className="sectionTitle">Nos partenaires</h2>
          <div className={styles.list}>
            {collaborators.map((collaborator) => (
              <div
                className={styles.logo}
                onClick={() => setSelected(collaborator)}
              >
                <img
                  title={collaborator.attributes.name}
                  src={`http://localhost:1337${collaborator.attributes.logo.data[0].attributes.url}`}
                />
              </div>
            ))}
          </div>

          <div className={styles.contact}>
            <h2>Et peut-être vous !</h2>
            <Link href="/contact">
              <a className={styles.sectionLink}>
                <span className="sectionLink">Nous contacter</span>
                <BigArrow className={styles.arrow} />
              </a>
            </Link>
          </div>
        </section>
        {selected && (
          <Collaborator
            logoURL={`http://localhost:1337${selected.attributes.logo.data[0].attributes.url}`}
            name={selected.attributes.name}
            field={selected.attributes.service}
            description={selected.attributes.description}
            advantages={selected.attributes.advantages}
            setCollaborator={setSelected}
          />
        )}
      </main>
      <Footer dark={true} />
    </>
  );
};

export default Collaborators;
